name=WiFiManagerESP
version=0.7.7
author=Olivier FOURNET
maintainer=Olivier FOURNET <olivier.fournet@free.fr>
sentence=Bibliothèque pour la gestion simplifiée des connexions WiFi sur ESP8266 et ESP32
paragraph=Support du mode point d'accès (AP), reconnexion automatique, gestion des événements WiFi, hostname personnalisable, multi-réseaux avec basculement automatique (failover), historique des connexions avec timestamps, et mDNS (Multicast DNS) avec services annoncés automatiquement.
category=Communication
url=https://github.com/Fo170/WiFiManagerESP
architectures=esp8266,esp32
license=GPL-3.0-only
includes=WiFiManagerESP.h
depends=
